FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY simple_etl.py .

## COPY . /app
CMD ["python", "simple_etl.py"]
## CMD python simple_etl.py